mutation {
  createMasterItems(
    input: {
      masterItems: [
        {
          name: "상품명 123"
          categoryCode: "100100100100"
          categoryInfoInput: {
            fullCode: "100100100100"
            depth1Code: "100000000000"
            depth1Name: "패션의류"
            depth2Code: "100100000000"
            depth2Name: "유니섹스/공용"
            depth3Code: "100100100000"
            depth3Name: "상의"
            depth4Code: "100100100100"
            depth4Name: "맨투맨"
          }
          price: 34000
          count: 9999
          userCode: "UNX-MTM-001"
          description: "맨투맨 상의 상품 상세설명~"
          imagesInput: [
            {
              order: 0
              url: "https://image.123.com/test.jpg"
              extendInfo: "{ something }"
            }
            {
              order: 1
              url: "https://image.123.com/test.jpg"
              extendInfo: "{ something }"
            }
            {
              order: 2
              url: "https://image.123.com/test.jpg"
              extendInfo: "{ something }"
            }
          ]
          selectionBaseInput: {
            type: Combined
            options: "['색상', '사이즈']"
            detailsInput: [
              {
                order:0
                count: 9999
                price: 1000
                userCode: "CODE123"
                valueInfo: " { something }"
                extendInfo: " { something }"
              }
              {
                order:1
                count: 9999
                price: 1000
                userCode: "CODE456"
                valueInfo: " { something }"
                extendInfo: " { something }"
              }
            ]
          }
          addOptionInfoListInput: [
            {
              order: 0
              name: "추가구성1"
              value: "추가구성1 값"
              price: 500
              count: 9999
              extendInfo: "{ something }"
            }
            {
              order: 1
              name: "추가구성2"
              value: "추가구성2 값"
              price: 500
              count: 9999
              extendInfo: "{ something }"
            }
          ]
          additionalInfoInput: {
            tax: TaxFree
            origin: "원산지가 어디"
            brand: "삼성물산"
          }
          sellingItemInfoInput: {
            # ...
          }
          extendInfoListInput: [
            {
              marketCode: "V"
              marketSubCode: "V001"
              info: " { some market extendInfo }"
            }
            {
              marketCode: "V"
              marketSubCode: "V003"
              info: " { some market extendInfo }"
            }
          ]
        }
      ]
    }
  )
  {
    ok
    error
    result {
      ok
      message
      masterItemId
    }
  }
}
