query	{
  getMasterItems(page:1, size:100)
  {
    ok
    error
    count
    masterItems {
      id
      name
      categoryCode
      categoryInfo
      {
        fullCode
        depth1Code
        depth1Name
        depth2Code
        depth2Name
        # ...
      }
      price
      count
      userCode
      description
      images {
        order
        url
        extendInfo {
          altMessage
        }
      }
      selectionBase {
        selectionId
        options
        # details {
        #   order
        #   count
        #   price
        #   valueInfo
        #   userCode
        #   extendInfo
        #   createdAt
        # }
      }
      # addOptionInfoList
      # {
      #   order
      #   name
      #   value
      #   price
      #   count
      #   extendInfo
      # }
      # additionalInfo
      # {
      #   tax
      #   origin
      #   brand
      # }
      # extendInfoList {
      #   marketCode
      #   marketSubCode
      #   info
      # }
      # sellingItemInfo {
      #   sendType
      #   sendPayType
      #   sourceMarket
      #   sellerId	
      #   sellingItemNo
      #   itemLink
      # }
      createdAt
      updatedAt
    }
  }
}