query	{
  getMasterItems(input: { ids: [800, 801, 802]})
  {
    ok
    error
    count
    masterItems {
      id
      name
      categoryCode
      categoryInfo
      {
        fullCode
        depth1Code
        depth1Name
        depth2Code
        depth2Name
        # ...
      }
      price
      count
      userCode
      description
      images {
        order
        url
        extendInfo {
          altMessage
        }
      }
      selectionBase {
        selectionId
        type
        options
        details {
          order
          count
          price
          values
          extendInfo {
            weight
            weightUnit
            capacity
            capacityUnit
          }
          userCode
          createdAt
        }
      }
      addOptionInfoList
      {
        order
        name
        value
        price
        count
      }
      additionalInfo
      {
        tax
        origin
        brand
      }
      extendInfoList {
        marketCode
        marketSubCode
        info
      }
      sellingItemInfo {
        sendType
        sendPayType
        sourceMarket
        sellerId	
        sellingItemNo
        itemLink
      }
      createdAt
      updatedAt
    }
  }
}